dist: trusty
sudo: false
language: c

addons:
  apt:
    packages:
    - lcov

before_script:
  - mkdir _build
  - cd _build

# configure, build and run the test suite with coverage support
script:
  - cmake -DTEST_COVERAGE=1 ..
  - cmake --build . --target suite
  - ctest

# generate coverage reports
after_script:
  - cmake --build . --target covGenerate
  - lcov -l _coverage/flecc_in_c.info
  - bash <(curl -s https://codecov.io/bash) -f _coverage/flecc_in_c.info
