language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq lcov
  - gem install coveralls-lcov

before_script:
  - mkdir _build
  - cd _build

# configure, build and run the test suite with coverage support
script:
  - cmake -DTEST_COVERAGE=1 ..
  - make suite
  - make coverage

# generate coverage reports
after_script:
  - lcov -l _coverage/flecc_in_c.info
  - coveralls-lcov _coverage/flecc_in_c.info
